//
//  __NAME__Presenter.swift
//  __PROJECT_NAME__
//
//  Created by __CREATOR__ on __DATE__.
//  Copyright © 2016 __AUTHOR__. All rights reserved.
//
//  Auto-generated by VIPCodeGenerator.
//

import Foundation

public protocol __NAME__PresenterInput {
    
}

public protocol __NAME__PresenterOutput: __NAME__ViewControllerInput {
    
}

public struct __NAME__Presenter: __NAME__PresenterInput {
    
    public weak var output: __NAME__PresenterOutput!
    
}
