//
//  __NAME__Configurator.swift
//  __PROJECT_NAME__
//
//  Created by __CREATOR__ on __DATE__.
//  Copyright © 2016 __AUTHOR__. All rights reserved.
//
//  Auto-generated by VIPCodeGenerator.
//

import Foundation

extension __NAME__ViewController: __NAME__PresenterOutput { }
extension __NAME__Interactor: __NAME__ViewControllerOutput { }
extension __NAME__Presenter: __NAME__InteractorOutput { }

public struct __NAME__Configurator {
    public static func configure(viewController: __NAME__ViewController) {
        let router = __NAME__Router(viewController: viewController)
        let presenter = __NAME__Presenter(output: viewController)
        let interactor = __NAME__Interactor(output: presenter)
        
        viewController.output = interactor
        viewController.router = router
    }
}
