//
//  __NAME__Interactor.swift
//  __PROJECT_NAME__
//
//  Created by __CREATOR__ on __DATE__.
//  Copyright © 2016 __AUTHOR__. All rights reserved.
//
//  Auto-generated by VIPCodeGenerator.
//

import Foundation

public protocol __NAME__InteractorInput {
    
}

public protocol __NAME__InteractorOutput: __NAME__PresenterInput {
    
}

public struct __NAME__Interactor: __NAME__InteractorInput {
    
    public var output: __NAME__InteractorOutput!
    
}
