//
//  __NAME__Router.swift
//  __PROJECT_NAME__
//
//  Created by __CREATOR__ on __DATE__.
//  Copyright © 2016 __AUTHOR__. All rights reserved.
//
//  Auto-generated by VIPCodeGenerator.
//

import Foundation

public protocol __NAME__RouterInput {
    
}

public struct __NAME__Router: __NAME__RouterInput {
 
    public weak var viewController: __NAME__ViewController!
    
}
