//
//  __NAME__Model.swift
//  __PROJECT_NAME__
//
//  Created by __CREATOR__ on __DATE__.
//  Copyright © 2016 __AUTHOR__. All rights reserved.
//
//  Auto-generated by VIPCodeGenerator.
//

import Foundation

public struct __NAME__Model {
    
    public struct Request {
        
    }
    
    public struct Response {
        
    }
    
    public struct ViewModel {

    }
    
}
