//
//  __NAME__ViewController.swift
//  __PROJECT_NAME__
//
//  Created by __CREATOR__ on __DATE__.
//  Copyright © 2016 __AUTHOR__. All rights reserved.
//
//  Auto-generated by VIPCodeGenerator.
//

import UIKit

public protocol __NAME__ViewControllerInput: class {
    
}

public protocol __NAME__ViewControllerOutput: __NAME__InteractorInput {
    
}

open class __NAME__ViewController: UIViewController, __NAME__ViewControllerInput {
    
    // MARK: Properties 
    
    open var output: __NAME__ViewControllerOutput!
    open var router: __NAME__RouterInput!
    
    // MARK: Life cycle
    
    open override func awakeFromNib() {
        super.awakeFromNib()
        __NAME__Configurator.configure(viewController: self)
    }
    
    override open func viewDidLoad() {
        super.viewDidLoad()
    }
}

